### ISSUE TITLE
Unable to download from https://repos.citusdata.com in docker image

### ISSUE THREAD

**Issue by enochcheung** [citusdata/packaging#11] opened 2016-09-13 00:38 UTC
Error:

```
$ docker exec -i citus_standalone '/usr/bin/apt-get' update
Get:1 http://apt.postgresql.org jessie-pgdg InRelease [33.8 kB]
Ign https://repos.citusdata.com jessie InRelease
Ign https://repos.citusdata.com jessie Release.gpg
Ign https://repos.citusdata.com jessie Release
Get:2 http://apt.postgresql.org jessie-pgdg/main amd64 Packages [92.9 kB]
Err https://repos.citusdata.com jessie/main Sources

Err https://repos.citusdata.com jessie/main amd64 Packages

Get:3 http://apt.postgresql.org jessie-pgdg/9.5 amd64 Packages [20 B]
Get:4 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [389 kB]
Ign http://httpredir.debian.org jessie InRelease
Get:6 http://httpredir.debian.org jessie-updates InRelease [142 kB]
Get:7 http://httpredir.debian.org jessie Release.gpg [2,373 B]
Get:8 http://httpredir.debian.org jessie Release [148 kB]
Get:9 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:10 http://httpredir.debian.org jessie/main amd64 Packages [9,032 kB]
Fetched 9,921 kB in 53s (185 kB/s)
W: Failed to fetch https://repos.citusdata.com/community/debian/dists/jessie/main/source/Sources

W: Failed to fetch https://repos.citusdata.com/community/debian/dists/jessie/main/binary-amd64/Packages

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Steps to reproduce:

```
docker run -d --name citus_standalone -p 5432:5432 citusdata/citus
docker exec -i citus_standalone '/usr/bin/apt-get' update
```

**Comment by lfittl** [comment] 2016-09-13 00:41
@jasonmp85 This is keeping @enochcheung on PGDG instead of our repository (see Slack) - anything obvious that jumps out from those error message?

**Comment by sumedhpathak** [comment] 2016-09-13 23:19
FWIW I get this error if I run apt-get update on Debian: (just an EC2 image):

```
W: Duplicate sources.list entry http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg/main amd64 Packages (/var/lib/apt/lists/apt.postgresql.org_pub_repos_apt_dists_jessie-pgdg_main_binary-amd64_Packages)
W: You may want to run apt-get update to correct these problems
```

This happens even before installing the new Citus packageCloud repo's. This doesn't match the error seen in Docker though. I was also able to reproduce this via the provided docker repro-steps.

**Comment by jasonmp85** [comment] 2016-09-16 22:03
Hey @enochcheung; thanks for the report!

After looking into this, it appears our cargo-culting of the `apt-get purge` line is the culprit.

Purging the `ca-certificates` package is fine for the PostgreSQL image from which we inherit, since it includes no SSL-enabled APT sources; however, Citus' package repo is served over HTTPS: without the certificates package, `apt-get` fails to contact the repo.

This is fine so long as users just want to run our image, but they can't extend it since our build process also clears the `apt-get` caches (meaning even a post-facto `apt-get install -y ca-certificates` would be impossible).

I've opened a pull request to preserve the certificates in the image, but have one question for you:

Is it enough for us to update our `latest` tag (which your example invocation implicitly uses), or would you prefer that we also update our e.g. `5`, `5.2`, and `5.2.1` tags?

Thanks!

**Comment by jasonmp85** [comment] 2016-09-16 22:19
> Is it enough for us to update our `latest` tag (which your example invocation implicitly uses), or would you prefer that we also update our e.g. `5`, `5.2`, and `5.2.1` tags?

Actually, I just realized I can push up a new tag named something like `v5.2.1-1` to reflect the Docker-related changes and the "right thing" should happen re: the Docker tags. So I'll rebuild them all after the merge.

**Comment by jasonmp85** [comment] 2016-09-16 23:38
`latest`, `5`, `5.2`, and `5.2.1` now include a fix for this issue. Closing; reopen if you can still reproduce the symptom.

**Closed as completed by jasonmp85** 2016-09-16 23:38 UTC
